In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

#pandas - panel data
- build on numpy library
- deals with Series and DataFrame

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Series  #single column and multiple row

In [4]:
data = [10,20,30,40,50]  #list

In [5]:
pd.Series(data)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
#with index name

In [7]:
pd.Series(data, index = ["a", "b", "c", "d", "e"])

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [9]:
# dictionary to Series

In [10]:
data = {"a":10, "b":20, "c":30}

In [11]:
pd.Series(data)

a    10
b    20
c    30
dtype: int64

In [12]:
pd.Series(data, name="Column1")

a    10
b    20
c    30
Name: Column1, dtype: int64

In [13]:
#DataFrame -

In [14]:
data = {
    "name":["Rahul","Parth", "Vinay"],
    "Age":[28,23,34],
    "City":["Wardha", "Amravati", "Wardha"] }

In [15]:
pd.Series(data)

name         [Rahul, Parth, Vinay]
Age                   [28, 23, 34]
City    [Wardha, Amravati, Wardha]
dtype: object

In [17]:
pd.DataFrame(data)

    name  Age      City
0  Rahul   28    Wardha
1  Parth   23  Amravati
2  Vinay   34    Wardha

In [26]:
df = pd.DataFrame([10,20,30], index= ["row1", "row2", "row3"], columns=["column1"])

In [27]:
df

      column1
row1       10
row2       20
row3       30

In [28]:
data = {
    "name":["Rahul","Parth", "Vinay"],
    "Age":[28,23,34],
    "City":["Wardha", "Amravati", "Wardha"] }

In [29]:
df = pd.DataFrame(data)

In [30]:
df

    name  Age      City
0  Rahul   28    Wardha
1  Parth   23  Amravati
2  Vinay   34    Wardha

#attribute

In [33]:
#.index - Index labels

In [32]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [34]:
#.columns

In [35]:
df.columns

Index(['name', 'Age', 'City'], dtype='object')

In [37]:
#.dtypes

In [38]:
df.dtypes

name    object
Age      int64
City    object
dtype: object

In [39]:
#.shape

In [40]:
df.shape

(3, 3)

In [41]:
#.ndim   - no. of dimentions

In [42]:
df.ndim

2

In [44]:
#.size - total elements

In [45]:
df.size

9

In [47]:
df.values

array([['Rahul', 28, 'Wardha'],
       ['Parth', 23, 'Amravati'],
       ['Vinay', 34, 'Wardha']], dtype=object)

#methods

In [48]:
#.head() - top rows from head

In [50]:
df.head()  #automatically 5 rows

    name  Age      City
0  Rahul   28    Wardha
1  Parth   23  Amravati
2  Vinay   34    Wardha

In [53]:
df.head(3)

    name  Age      City
0  Rahul   28    Wardha
1  Parth   23  Amravati
2  Vinay   34    Wardha

In [55]:
#.tail() - for last rows

In [56]:
df.tail()

    name  Age      City
0  Rahul   28    Wardha
1  Parth   23  Amravati
2  Vinay   34    Wardha

In [57]:
df.tail(1)

    name  Age    City
2  Vinay   34  Wardha

In [58]:
#.info()

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   Age     3 non-null      int64
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [60]:
#.describe()

In [61]:
df.describe()

             Age
count   3.000000
mean   28.333333
std     5.507571
min    23.000000
25%    25.500000
50%    28.000000
75%    31.000000
max    34.000000

In [63]:
df.describe(include="all")

         name        Age    City
count       3   3.000000       3
unique      3        NaN       2
top     Rahul        NaN  Wardha
freq        1        NaN       2
mean      NaN  28.333333     NaN
std       NaN   5.507571     NaN
min       NaN  23.000000     NaN
25%       NaN  25.500000     NaN
50%       NaN  28.000000     NaN
75%       NaN  31.000000     NaN
max       NaN  34.000000     NaN

In [64]:
#.sample()- randomly select the required data1

In [68]:
df.sample(2)

    name  Age      City
2  Vinay   34    Wardha
1  Parth   23  Amravati

#pandas read function

In [69]:
#pd.read - function

In [70]:
df = pd.read_csv("/content/sample_data/california_housing_test.csv")
#csv - comma seperated values

In [71]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [72]:
df.sample(2)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
1076,-122.26,37.84,49.0,713.0,202.0,462.0,189.0,1.0250,118800.0
1512,-122.30,38.00,34.0,1712.0,317.0,956.0,341.0,4.4394,162000.0

In [73]:
#single column access

In [74]:
df['housing_median_age']

0       27.0
1       43.0
2       27.0
3       28.0
4       19.0
        ...
2995    23.0
2996    27.0
2997    10.0
2998    40.0
2999    42.0
Name: housing_median_age, Length: 3000, dtype: float64

In [75]:
#multiple columns
df[["housing_median_age", "total_rooms"]]

      housing_median_age  total_rooms
0                   27.0       3885.0
1                   43.0       1510.0
2                   27.0       3589.0
3                   28.0         67.0
4                   19.0       1241.0
...                  ...          ...
2995                23.0       1450.0
2996                27.0       5257.0
2997                10.0        956.0
2998                40.0         96.0
2999                42.0       1765.0

[3000 rows x 2 columns]

In [76]:
# .iloc - index location

In [79]:
df.iloc[0]

longitude               -122.0500
latitude                  37.3700
housing_median_age        27.0000
total_rooms             3885.0000
total_bedrooms           661.0000
population              1537.0000
households               606.0000
median_income              6.6085
median_house_value    344700.0000
Name: 0, dtype: float64

In [78]:
df.head(13)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0
10,-118.24,33.98,45.0,972.0,249.0,1288.0,261.0,2.2054,125000.0
11,-119.12,35.85,37.0,736.0,166.0,564.0,138.0,2.4167,58300.0
12,-121.93,37.25,36.0,1089.0,182.0,535.0,170.0,4.6900,252600.0

In [80]:
df1 = pd.DataFrame([10,20,30], index= ["row1", "row2", "row3"])

In [81]:
df1

       0
row1  10
row2  20
row3  30

In [82]:
df1.iloc[1]

0    20
Name: row2, dtype: int64

In [86]:
df1.loc["row2"]

0    20
Name: row2, dtype: int64

In [87]:
df['housing_median_age'].describe()

count    3000.000000
mean       28.845333
std        12.555396
min         1.000000
25%        18.000000
50%        29.000000
75%        37.000000
max        52.000000
Name: housing_median_age, dtype: float64

In [89]:
df[df['housing_median_age'] < 2]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.875,141700.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.625,55000.0

In [90]:
df['housing_median_age'] < 2

0       False
1       False
2       False
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Name: housing_median_age, Length: 3000, dtype: bool

In [102]:
house_age_data = df.sort_values("housing_median_age")

In [105]:
df3 = house_age_data.reset_index()

In [106]:
df3

,index,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0
1,1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
2,2452,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0
3,2429,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0
4,1050,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0
...,...,...,...,...,...,...,...,...,...,...
2995,26,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0
2996,36,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0
2997,2965,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0
2998,2970,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0
2999,2972,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0

In [109]:
#new columns creation
df3["New_age"] = df3['housing_median_age'] * 2

In [108]:
df3

,index,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_age
0,842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0,2.0
1,1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0,2.0
2,2452,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0,4.0
3,2429,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0,4.0
4,1050,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...
2995,26,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0,104.0
2996,36,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0,104.0
2997,2965,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0,104.0
2998,2970,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0,104.0
2999,2972,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0,104.0

In [110]:
#deleting the column

In [111]:
df3.drop("index", axis = 1)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_age
0,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0,2.0
1,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0,2.0
2,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0,4.0
3,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0,4.0
4,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0,4.0
...,...,...,...,...,...,...,...,...,...,...
2995,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0,104.0
2996,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0,104.0
2997,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0,104.0
2998,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0,104.0
2999,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0,104.0

In [112]:
df3

,index,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_age
0,842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0,2.0
1,1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0,2.0
2,2452,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0,4.0
3,2429,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0,4.0
4,1050,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...
2995,26,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0,104.0
2996,36,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0,104.0
2997,2965,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0,104.0
2998,2970,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0,104.0
2999,2972,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0,104.0

In [113]:
#inplace = True for permenent drop
df3.drop("index", axis = 1, inplace= True)

In [114]:
df3

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,New_age
0,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0,2.0
1,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0,2.0
2,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0,4.0
3,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0,4.0
4,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0,4.0
...,...,...,...,...,...,...,...,...,...,...
2995,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0,104.0
2996,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0,104.0
2997,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0,104.0
2998,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0,104.0
2999,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0,104.0

In [116]:
df3.drop("New_age", axis = 1, inplace= True)

In [117]:
df3

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0
1,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
2,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0
3,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0
4,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0
...,...,...,...,...,...,...,...,...,...
2995,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0
2996,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0
2997,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0
2998,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0
2999,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0

In [118]:
df1

       0
row1  10
row2  20
row3  30

In [120]:
df1.rename(columns={0:"column1"})

      column1
row1       10
row2       20
row3       30

In [121]:
df3.rename(columns={"housing_median_age":"house_age"})

,longitude,latitude,house_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0
1,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
2,-117.64,33.87,2.0,17470.0,2727.0,5964.0,1985.0,6.2308,257900.0
3,-117.20,33.58,2.0,30450.0,5033.0,9419.0,3197.0,4.5936,174300.0
4,-121.96,37.74,2.0,200.0,20.0,25.0,9.0,15.0001,350000.0
...,...,...,...,...,...,...,...,...,...
2995,-122.42,37.76,52.0,3587.0,1030.0,2259.0,979.0,2.5403,250000.0
2996,-122.53,37.97,52.0,1560.0,451.0,700.0,419.0,2.5125,270800.0
2997,-122.44,37.71,52.0,2711.0,591.0,1848.0,524.0,3.9567,251500.0
2998,-122.47,37.77,52.0,2241.0,443.0,1042.0,377.0,4.1635,398400.0
2999,-118.14,34.17,52.0,2667.0,486.0,1681.0,504.0,4.0524,173100.0

# missing values

In [123]:
df.isnull()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
2995,False,False,False,False,False,False,False,False,False
2996,False,False,False,False,False,False,False,False,False
2997,False,False,False,False,False,False,False,False,False
2998,False,False,False,False,False,False,False,False,False
2999,False,False,False,False,False,False,False,False,False

In [124]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
dtype: int64

In [125]:
df.notnull().sum()

longitude             3000
latitude              3000
housing_median_age    3000
total_rooms           3000
total_bedrooms        3000
population            3000
households            3000
median_income         3000
median_house_value    3000
dtype: int64

In [127]:
#replacing the null values
df.fillna("tushar")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [129]:
df.dropna(inplace=True)

In [130]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

#aggregation

In [132]:
df['total_rooms'].sum()

np.float64(7798736.0)

In [133]:
df['total_rooms'].mean()

np.float64(2599.578666666667)

In [134]:
df['total_rooms'].median()

2106.0

In [136]:
df['total_rooms'].min()

6.0

In [137]:
df['total_rooms'].max()

30450.0

In [142]:
newdf = df.groupby(["housing_median_age","total_rooms"])

In [144]:
newdf.mean()

                                longitude  latitude  total_bedrooms  \
housing_median_age total_rooms
1.0                6.0            -116.95     33.86             2.0
                   83.0           -117.95     35.08            15.0
2.0                158.0          -122.29     37.82            43.0
                   200.0          -121.96     37.74            20.0
                   718.0          -117.51     34.16            98.0
...                                   ...       ...             ...
52.0               4220.0         -118.21     33.97           908.0
                   4407.0         -122.42     37.76          1192.0
                   4513.0         -122.27     41.20           985.0
                   5604.0         -122.44     37.77          1268.0
                   6186.0         -122.43     37.79          1566.0

                                population  households  median_income  \
housing_median_age total_rooms
1.0                6.0                 8.0         2.0         1.6250
                   83.0               32.0        15.0         4.8750
2.0                158.0              94.0        57.0         2.5625
                   200.0              25.0         9.0        15.0001
                   718.0             119.0        50.0         4.1000
...                                    ...         ...            ...
52.0               4220.0           3731.0       892.0         3.1901
                   4407.0           2280.0      1076.0         3.3937
                   4513.0           1926.0       815.0         1.5923
                   5604.0           2023.0      1196.0         4.4085
                   6186.0           2065.0      1374.0         5.8543

                                median_house_value
housing_median_age total_rooms
1.0                6.0                     55000.0
                   83.0                   141700.0
2.0                158.0                   60000.0
                   200.0                  350000.0
                   718.0                  315000.0
...                                            ...
52.0               4220.0                 167600.0
                   4407.0                 270000.0
                   4513.0                  56000.0
                   5604.0                 400000.0
                   6186.0                 500001.0

[2974 rows x 7 columns]

In [146]:
df['housing_median_age'].value_counts()

housing_median_age
52.0    173
35.0    118
36.0    115
16.0    107
34.0    102
17.0    100
32.0     91
37.0     88
26.0     88
25.0     86
33.0     85
15.0     77
30.0     76
19.0     76
18.0     76
24.0     75
29.0     75
27.0     74
38.0     64
20.0     63
21.0     61
22.0     60
28.0     58
31.0     57
14.0     57
43.0     56
41.0     56
39.0     55
23.0     53
45.0     51
44.0     51
42.0     51
40.0     43
13.0     41
46.0     41
12.0     41
11.0     41
5.0      39
48.0     34
10.0     30
4.0      28
9.0      27
8.0      25
6.0      25
47.0     22
49.0     21
7.0      20
50.0     16
3.0      12
51.0     11
2.0       6
1.0       2
Name: count, dtype: int64

In [147]:
import seaborn as sns

In [148]:
titanic = sns.load_dataset("titanic")

In [150]:
titanic.head(1)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False

In [153]:
titanic.shape

(891, 15)

In [154]:
titanic['sex'].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [162]:
titanic.groupby("sex")['survived'].mean()*100

#() - categorical columns
#[] - numerical columns

sex
female    74.203822
male      18.890815
Name: survived, dtype: float64

In [163]:
titanic.groupby(["sex", "pclass"])['survived'].mean()*100

#() - categorical columns
#[] - numerical columns

sex     pclass
female  1         96.808511
        2         92.105263
        3         50.000000
male    1         36.885246
        2         15.740741
        3         13.544669
Name: survived, dtype: float64

In [164]:
titanic.groupby(["pclass", "sex"])['survived'].mean()*100

#() - categorical columns
#[] - numerical columns

pclass  sex
1       female    96.808511
        male      36.885246
2       female    92.105263
        male      15.740741
3       female    50.000000
        male      13.544669
Name: survived, dtype: float64

In [167]:
titanic.groupby(["pclass", "sex"])['survived'].mean().unstack()

#() - categorical columns
#[] - numerical columns

sex       female      male
pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

In [168]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [169]:
titanic['age'].describe()

count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: age, dtype: float64

In [170]:
age_bins = [0,12,18,35,60,80]
age_labels = ["child", "Teen", "Young", "Adult", "Senior"]

titanic["age_group"] = pd.cut(titanic["age"],
                              bins=age_bins,
                              labels= age_labels)

In [175]:
titanic[["age", "age_group"]].head()

    age age_group
0  22.0     Young
1  38.0     Adult
2  26.0     Young
3  35.0     Young
4  35.0     Young